
x==========x]
[2024-06-04 12:45:08,566: INFO: main: *******************]
[2024-06-04 12:45:08,566: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-04 12:45:08,566: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-04 12:45:08,575: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-04 12:45:08,578: INFO: common: created directory at: artifacts]
[2024-06-04 12:45:09,184: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-04 12:45:47,349: INFO: common: json file saved at: scores.json]
[2024-06-04 12:45:47,359: INFO: common: json file saved at: scores.json]
[2024-06-04 12:46:06,747: INFO: helpers: Initialized MLflow to track repo "TTNamUS/Kidney-Disease-Classification-Project"]
[2024-06-04 12:46:06,747: INFO: helpers: Repository TTNamUS/Kidney-Disease-Classification-Project initialized!]
[2024-06-04 12:51:08,882: INFO: main: *******************]
[2024-06-04 12:51:08,882: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-04 12:51:08,882: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-04 12:51:08,889: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-04 12:51:08,889: INFO: common: created directory at: artifacts]
[2024-06-04 12:51:09,460: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-04 12:51:48,451: INFO: common: json file saved at: scores.json]
[2024-06-04 12:51:48,451: INFO: common: json file saved at: scores.json]
[2024-06-04 12:52:05,432: INFO: helpers: Initialized MLflow to track repo "TTNamUS/Kidney-Disease-Classification-Project"]
[2024-06-04 12:52:05,432: INFO: helpers: Repository TTNamUS/Kidney-Disease-Classification-Project initialized!]
[2024-06-04 12:52:20,134: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /TTNamUS/Kidney-Disease-Classification-Project.mlflow/api/2.0/mlflow/runs/create]
[2024-06-04 12:55:24,981: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-06-04 12:55:49,718: INFO: main: *******************]
[2024-06-04 12:55:49,719: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-04 12:55:49,721: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-04 12:55:49,726: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-04 12:55:49,727: INFO: common: created directory at: artifacts]
[2024-06-04 12:55:50,133: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-04 12:56:24,458: INFO: common: json file saved at: scores.json]
[2024-06-04 12:56:24,458: INFO: common: json file saved at: scores.json]
[2024-06-04 12:56:26,802: INFO: helpers: Initialized MLflow to track repo "TTNamUS/Kidney-Disease-Classification-Project"]
[2024-06-04 12:56:26,802: INFO: helpers: Repository TTNamUS/Kidney-Disease-Classification-Project initialized!]
[2024-06-04 12:57:32,022: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-06-04 16:01:00,811: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-06-04 16:01:00,815: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-04 16:01:00,817: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-04 16:01:00,817: INFO: common: created directory at: artifacts]
[2024-06-04 16:01:00,818: INFO: common: created directory at: artifacts/data_ingestion]
[2024-06-04 16:01:00,818: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-04 16:01:19,725: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-06-04 16:01:20,980: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-06-04 16:02:21,144: INFO: stage_02_prepare_base_model: *******************]
[2024-06-04 16:02:21,146: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-06-04 16:02:21,152: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-04 16:02:21,158: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-04 16:02:21,158: INFO: common: created directory at: artifacts]
[2024-06-04 16:02:21,159: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-06-04 16:02:22,544: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-04 16:02:25,387: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-04 16:02:25,786: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-06-04 16:02:37,723: INFO: stage_03_model_training: *******************]
[2024-06-04 16:02:37,723: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-06-04 16:02:37,728: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-04 16:02:37,731: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-04 16:02:37,732: INFO: common: created directory at: artifacts]
[2024-06-04 16:02:37,733: INFO: common: created directory at: artifacts\training]
[2024-06-04 16:02:38,342: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-04 16:05:22,656: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-06-04 16:05:23,458: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-06-04 16:05:57,433: INFO: stage_04_model_evaluation: *******************]
[2024-06-04 16:05:57,434: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-04 16:05:57,440: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-04 16:05:57,443: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-04 16:05:57,443: INFO: common: created directory at: artifacts]
[2024-06-04 16:05:58,725: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-04 16:06:57,652: INFO: common: json file saved at: scores.json]
[2024-06-04 16:06:57,662: INFO: common: json file saved at: scores.json]
[2024-06-04 16:07:00,583: INFO: helpers: Initialized MLflow to track repo "TTNamUS/Kidney-Disease-Classification-Project"]
[2024-06-04 16:07:00,585: INFO: helpers: Repository TTNamUS/Kidney-Disease-Classification-Project initialized!]
[2024-06-04 16:08:22,394: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-06-04 16:16:09,319: INFO: stage_04_model_evaluation: *******************]
[2024-06-04 16:16:09,323: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-06-04 16:16:09,340: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-06-04 16:16:09,345: INFO: common: yaml file: params.yaml loaded successfully]
[2024-06-04 16:16:09,347: INFO: common: created directory at: artifacts]
[2024-06-04 16:16:11,656: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-04 16:17:01,715: INFO: common: json file saved at: scores.json]
[2024-06-04 16:17:01,722: INFO: common: json file saved at: scores.json]
[2024-06-04 16:17:01,728: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-06-04 16:25:59,844: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2024-06-04 16:25:59,844: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-06-04 16:26:07,723: INFO: _internal: 127.0.0.1 - - [04/Jun/2024 16:26:07] "GET / HTTP/1.1" 200 -]
[2024-06-04 16:26:27,537: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\LearnAI\Kidney-Disease-Classification-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\my folder\my learning\ttnamus\learnai\kidney-disease-classification-project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-06-04 16:26:27,557: INFO: _internal: 127.0.0.1 - - [04/Jun/2024 16:26:27] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-06-04 16:27:40,040: INFO: _internal: 127.0.0.1 - - [04/Jun/2024 16:27:40] "GET / HTTP/1.1" 200 -]
[2024-06-04 16:27:48,426: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\LearnAI\Kidney-Disease-Classification-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\my folder\my learning\ttnamus\learnai\kidney-disease-classification-project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-06-04 16:27:48,436: INFO: _internal: 127.0.0.1 - - [04/Jun/2024 16:27:48] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-06-04 16:29:15,512: INFO: _internal: 127.0.0.1 - - [04/Jun/2024 16:29:15] "GET / HTTP/1.1" 200 -]
[2024-06-04 16:32:06,192: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2024-06-04 16:32:06,195: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-06-04 16:32:21,714: INFO: _internal: 127.0.0.1 - - [04/Jun/2024 16:32:21] "GET / HTTP/1.1" 200 -]
[2024-06-04 16:32:42,393: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\LearnAI\Kidney-Disease-Classification-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\my folder\my learning\ttnamus\learnai\kidney-disease-classification-project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-06-04 16:32:42,413: INFO: _internal: 127.0.0.1 - - [04/Jun/2024 16:32:42] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-06-04 23:49:59,687: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2024-06-04 23:49:59,689: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-06-04 23:50:48,229: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2024-06-04 23:50:48,229: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-06-04 23:50:51,563: INFO: _internal: 127.0.0.1 - - [04/Jun/2024 23:50:51] "GET / HTTP/1.1" 200 -]
[2024-06-04 23:50:58,073: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\LearnAI\Kidney-Disease-Classification-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\my folder\my learning\ttnamus\learnai\kidney-disease-classification-project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-06-04 23:50:58,103: INFO: _internal: 127.0.0.1 - - [04/Jun/2024 23:50:58] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-06-04 23:54:11,568: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2024-06-04 23:54:11,568: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-06-04 23:54:13,912: INFO: _internal: 127.0.0.1 - - [04/Jun/2024 23:54:13] "GET / HTTP/1.1" 200 -]
[2024-06-04 23:54:21,823: INFO: _internal: 127.0.0.1 - - [04/Jun/2024 23:54:21] "GET / HTTP/1.1" 200 -]
[2024-06-04 23:54:27,430: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\LearnAI\Kidney-Disease-Classification-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\my folder\my learning\ttnamus\learnai\kidney-disease-classification-project\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-06-04 23:54:27,441: INFO: _internal: 127.0.0.1 - - [04/Jun/2024 23:54:27] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-06-04 23:56:01,207: INFO: _internal: 127.0.0.1 - - [04/Jun/2024 23:56:01] "GET / HTTP/1.1" 200 -]
[2024-06-05 00:03:30,204: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2024-06-05 00:03:30,205: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-06-05 00:03:37,249: INFO: _internal: 127.0.0.1 - - [05/Jun/2024 00:03:37] "GET / HTTP/1.1" 200 -]
[2024-06-05 00:03:45,563: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-05 00:03:48,486: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\LearnAI\Kidney-Disease-Classification-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\my folder\my learning\ttnamus\learnai\kidney-disease-classification-project\src\cnnClassifier\pipeline\prediction.py", line 22, in predict
    result = np.argmax(model.predict(test_image), axis=1)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-38: character maps to <undefined>
[2024-06-05 00:03:48,592: INFO: _internal: 127.0.0.1 - - [05/Jun/2024 00:03:48] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-06-05 00:04:24,559: INFO: _internal: 127.0.0.1 - - [05/Jun/2024 00:04:24] "GET / HTTP/1.1" 200 -]
[2024-06-05 00:08:16,460: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-05 00:08:19,456: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\LearnAI\Kidney-Disease-Classification-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\my folder\my learning\ttnamus\learnai\kidney-disease-classification-project\src\cnnClassifier\pipeline\prediction.py", line 22, in predict
    result = np.argmax(model.predict(test_image), axis=1)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\drive\miniconda3\envs\kidney\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-38: character maps to <undefined>
[2024-06-05 00:08:19,494: INFO: _internal: 127.0.0.1 - - [05/Jun/2024 00:08:19] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-06-05 10:42:39,945: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.12:8080]
[2024-06-05 10:42:39,947: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-06-05 10:43:23,602: INFO: _internal: 127.0.0.1 - - [05/Jun/2024 10:43:23] "GET / HTTP/1.1" 200 -]
[2024-06-05 10:43:37,779: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-06-05 10:43:39,527: INFO: _internal: 127.0.0.1 - - [05/Jun/2024 10:43:39] "POST /predict HTTP/1.1" 200 -]
[2024-12-12 16:43:54,991: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-12 16:43:54,994: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-12 16:43:54,995: INFO: common: created directory at: artifacts]
[2024-12-12 16:43:54,997: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-12 16:43:54,999: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-12 16:45:39,547: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-12 16:53:35,521: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-12 16:53:35,524: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-12 16:53:35,526: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-12 16:53:35,527: INFO: common: created directory at: artifacts]
[2024-12-12 16:53:35,527: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-12 16:53:35,527: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-12 16:54:19,855: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-12 16:54:20,548: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-12 21:38:59,564: INFO: main: *******************]
[2024-12-12 21:38:59,566: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-12 21:38:59,572: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-12 21:38:59,580: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-12 21:38:59,580: INFO: common: created directory at: artifacts]
[2024-12-12 21:38:59,581: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-12 21:39:50,513: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-12-12 21:39:50,704: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-12-12 21:39:50,861: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-12 21:44:46,986: INFO: main: *******************]
[2024-12-12 21:44:46,986: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-12-12 21:44:46,993: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-12 21:44:46,996: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-12 21:44:46,997: INFO: common: created directory at: artifacts]
[2024-12-12 21:44:46,997: INFO: common: created directory at: artifacts\training]
[2024-12-12 21:44:47,769: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-12 21:47:26,257: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-12-12 21:47:26,608: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-12 22:24:45,051: INFO: main: *******************]
[2024-12-12 22:24:45,051: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-12 22:24:45,055: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-12 22:24:45,058: INFO: common: yaml file: config\params.yaml loaded successfully]
[2024-12-12 22:24:45,059: INFO: common: yaml file: config\service.yaml loaded successfully]
[2024-12-12 22:24:45,060: INFO: common: created directory at: artifacts]
[2024-12-12 22:24:45,444: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-12 22:25:23,277: INFO: common: json file saved at: scores.json]
[2024-12-12 22:25:23,279: INFO: common: json file saved at: scores.json]
[2024-12-12 22:25:23,279: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-12 22:25:55,625: INFO: main: *******************]
[2024-12-12 22:25:55,625: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-12 22:25:55,629: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-12 22:25:55,632: INFO: common: yaml file: config\params.yaml loaded successfully]
[2024-12-12 22:25:55,633: INFO: common: yaml file: config\service.yaml loaded successfully]
[2024-12-12 22:25:55,633: INFO: common: created directory at: artifacts]
[2024-12-12 22:25:56,123: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-12 22:26:36,665: INFO: common: json file saved at: scores.json]
[2024-12-12 22:26:36,666: INFO: common: json file saved at: scores.json]
[2024-12-12 22:26:37,544: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2024-12-12 22:26:37,556: INFO: helpers: Accessing as TTNamUS]
[2024-12-12 22:26:38,231: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/TTNamUS/Kidney-Disease-Classification-Project "HTTP/1.1 200 OK"]
[2024-12-12 22:26:38,917: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2024-12-12 22:26:38,920: INFO: helpers: Initialized MLflow to track repo "TTNamUS/Kidney-Disease-Classification-Project"]
[2024-12-12 22:26:38,922: INFO: helpers: Repository TTNamUS/Kidney-Disease-Classification-Project initialized!]
[2024-12-12 22:27:56,867: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-12 22:57:36,516: INFO: main: *******************]
[2024-12-12 22:57:36,517: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-12 22:57:36,521: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-12 22:57:36,524: INFO: common: yaml file: config\params.yaml loaded successfully]
[2024-12-12 22:57:36,525: INFO: common: yaml file: config\services.yaml loaded successfully]
[2024-12-12 22:57:36,526: INFO: common: created directory at: artifacts]
[2024-12-12 22:57:37,016: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-12 22:58:32,950: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2024-12-12 22:58:32,961: INFO: helpers: Accessing as TTNamUS]
[2024-12-12 22:58:33,710: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/TTNamUS/Kidney-Disease-Classification-Project "HTTP/1.1 200 OK"]
[2024-12-12 22:58:34,334: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2024-12-12 22:58:34,339: INFO: helpers: Initialized MLflow to track repo "TTNamUS/Kidney-Disease-Classification-Project"]
[2024-12-12 22:58:34,342: INFO: helpers: Repository TTNamUS/Kidney-Disease-Classification-Project initialized!]
[2024-12-12 22:59:52,680: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-12 23:09:18,790: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-12 23:09:18,827: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.17:8080]
[2024-12-12 23:09:18,827: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-12-12 23:09:23,309: INFO: _internal: 127.0.0.1 - - [12/Dec/2024 23:09:23] "GET / HTTP/1.1" 200 -]
[2024-12-12 23:09:59,803: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-12 23:10:02,755: INFO: _internal: 127.0.0.1 - - [12/Dec/2024 23:10:02] "POST /predict HTTP/1.1" 200 -]
[2024-12-12 23:23:46,446: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-12 23:23:46,453: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-12 23:23:46,457: INFO: common: yaml file: config\params.yaml loaded successfully]
[2024-12-12 23:23:46,461: INFO: common: yaml file: config\services.yaml loaded successfully]
[2024-12-12 23:23:46,462: INFO: common: created directory at: artifacts]
[2024-12-12 23:23:46,463: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-12 23:23:46,464: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-12 23:24:05,097: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-12 23:24:06,606: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-12 23:31:18,693: INFO: stage_02_prepare_base_model: *******************]
[2024-12-12 23:31:18,693: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-12 23:31:18,698: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-12 23:31:18,701: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-12 23:31:18,702: INFO: common: yaml file: config\services.yaml loaded successfully]
[2024-12-12 23:31:18,703: INFO: common: created directory at: artifacts]
[2024-12-12 23:31:18,703: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-12 23:31:19,297: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-12-12 23:31:19,511: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-12-12 23:31:19,661: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-12 23:31:28,008: INFO: stage_03_model_training: *******************]
[2024-12-12 23:31:28,009: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-12-12 23:31:28,012: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-12 23:31:28,015: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-12 23:31:28,017: INFO: common: yaml file: config\services.yaml loaded successfully]
[2024-12-12 23:31:28,018: INFO: common: created directory at: artifacts]
[2024-12-12 23:31:28,018: INFO: common: created directory at: artifacts\training]
[2024-12-12 23:31:28,370: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-12 23:33:46,369: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-12-12 23:33:46,721: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-12 23:33:59,486: INFO: stage_04_model_evaluation: *******************]
[2024-12-12 23:33:59,486: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-12 23:33:59,490: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-12 23:33:59,493: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-12 23:33:59,495: INFO: common: yaml file: config\services.yaml loaded successfully]
[2024-12-12 23:33:59,496: INFO: common: created directory at: artifacts]
[2024-12-12 23:33:59,942: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-12 23:34:43,598: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2024-12-12 23:34:43,609: INFO: helpers: Accessing as TTNamUS]
[2024-12-12 23:34:44,327: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/TTNamUS/Kidney-Disease-Classification-Project "HTTP/1.1 200 OK"]
[2024-12-12 23:34:44,993: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2024-12-12 23:34:45,000: INFO: helpers: Initialized MLflow to track repo "TTNamUS/Kidney-Disease-Classification-Project"]
[2024-12-12 23:34:45,002: INFO: helpers: Repository TTNamUS/Kidney-Disease-Classification-Project initialized!]
[2024-12-12 23:36:00,533: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-12 23:41:16,295: INFO: stage_04_model_evaluation: *******************]
[2024-12-12 23:41:16,296: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-12 23:41:16,298: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-12 23:41:16,300: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-12 23:41:16,300: INFO: common: yaml file: config\services.yaml loaded successfully]
[2024-12-12 23:41:16,301: INFO: common: created directory at: artifacts]
[2024-12-12 23:41:16,572: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-12 23:41:57,197: INFO: common: json file saved at: scores.json]
[2024-12-12 23:41:58,109: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2024-12-12 23:41:58,127: INFO: helpers: Accessing as TTNamUS]
[2024-12-12 23:41:58,779: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/TTNamUS/Kidney-Disease-Classification-Project "HTTP/1.1 200 OK"]
[2024-12-12 23:41:59,411: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2024-12-12 23:41:59,420: INFO: helpers: Initialized MLflow to track repo "TTNamUS/Kidney-Disease-Classification-Project"]
[2024-12-12 23:41:59,422: INFO: helpers: Repository TTNamUS/Kidney-Disease-Classification-Project initialized!]
[2024-12-12 23:43:23,905: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-13 00:10:01,347: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-12-13 00:10:01,350: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 00:10:01,351: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-13 00:10:01,352: INFO: common: yaml file: config\services.yaml loaded successfully]
[2024-12-13 00:10:01,353: INFO: common: created directory at: artifacts]
[2024-12-13 00:10:01,353: INFO: common: created directory at: artifacts/data_ingestion]
[2024-12-13 00:10:01,353: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-13 00:10:16,430: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-12-13 00:10:17,031: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-12-13 00:10:23,101: INFO: stage_02_prepare_base_model: *******************]
[2024-12-13 00:10:23,101: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-12-13 00:10:23,104: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 00:10:23,106: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-13 00:10:23,106: INFO: common: yaml file: config\services.yaml loaded successfully]
[2024-12-13 00:10:23,106: INFO: common: created directory at: artifacts]
[2024-12-13 00:10:23,108: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-12-13 00:10:23,438: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-12-13 00:10:23,581: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-12-13 00:10:23,671: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-12-13 00:10:29,324: INFO: stage_03_model_training: *******************]
[2024-12-13 00:10:29,324: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-12-13 00:10:29,327: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 00:10:29,328: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-13 00:10:29,329: INFO: common: yaml file: config\services.yaml loaded successfully]
[2024-12-13 00:10:29,329: INFO: common: created directory at: artifacts]
[2024-12-13 00:10:29,330: INFO: common: created directory at: model]
[2024-12-13 00:10:29,603: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 00:12:19,523: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-12-13 00:12:19,899: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-13 00:13:00,753: INFO: stage_03_model_training: *******************]
[2024-12-13 00:13:00,753: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-12-13 00:13:00,756: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 00:13:00,758: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-13 00:13:00,759: INFO: common: yaml file: config\services.yaml loaded successfully]
[2024-12-13 00:13:00,760: INFO: common: created directory at: artifacts]
[2024-12-13 00:13:00,760: INFO: common: created directory at: model]
[2024-12-13 00:13:01,081: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 00:15:12,203: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-12-13 00:15:12,480: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-12-13 00:15:26,999: INFO: stage_04_model_evaluation: *******************]
[2024-12-13 00:15:27,000: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-12-13 00:15:27,011: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 00:15:27,018: INFO: common: yaml file: params.yaml loaded successfully]
[2024-12-13 00:15:27,022: INFO: common: yaml file: config\services.yaml loaded successfully]
[2024-12-13 00:15:27,022: INFO: common: created directory at: artifacts]
[2024-12-13 00:15:27,669: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 00:16:10,639: INFO: common: json file saved at: scores.json]
[2024-12-13 00:16:11,893: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2024-12-13 00:16:11,908: INFO: helpers: Accessing as TTNamUS]
[2024-12-13 00:16:12,669: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/repos/TTNamUS/Kidney-Disease-Classification-Project "HTTP/1.1 200 OK"]
[2024-12-13 00:16:13,299: INFO: _client: HTTP Request: GET https://dagshub.com/api/v1/user "HTTP/1.1 200 OK"]
[2024-12-13 00:16:13,303: INFO: helpers: Initialized MLflow to track repo "TTNamUS/Kidney-Disease-Classification-Project"]
[2024-12-13 00:16:13,304: INFO: helpers: Repository TTNamUS/Kidney-Disease-Classification-Project initialized!]
[2024-12-13 00:17:40,622: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-12-13 10:23:44,773: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 10:23:44,796: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.17:8080]
[2024-12-13 10:23:44,796: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-12-13 10:23:54,933: INFO: _internal: 127.0.0.1 - - [13/Dec/2024 10:23:54] "OPTIONS /predict HTTP/1.1" 200 -]
[2024-12-13 10:23:55,197: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'training'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'training'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'training'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'training'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'training'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'training'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'training'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\KidneyProject\Kidney-Disease-Classification-Project\venv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\KidneyProject\Kidney-Disease-Classification-Project\venv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\KidneyProject\Kidney-Disease-Classification-Project\venv\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\KidneyProject\Kidney-Disease-Classification-Project\venv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\KidneyProject\Kidney-Disease-Classification-Project\venv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\KidneyProject\Kidney-Disease-Classification-Project\venv\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\KidneyProject\Kidney-Disease-Classification-Project\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "d:\my folder\my learning\ttnamus\kidneyproject\kidney-disease-classification-project\src\cnnClassifier\pipeline\prediction.py", line 19, in predict
    model = load_model(os.path.join(self.config.training.trained_model_path))
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'training'"
[2024-12-13 10:23:55,220: INFO: _internal: 127.0.0.1 - - [13/Dec/2024 10:23:55] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-12-13 11:03:58,564: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:04:00,215: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:05:39,864: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:08:59,875: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:18:12,756: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:18:14,464: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:18:15,027: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:18:15,246: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:18:15,412: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:24:54,792: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:03,093: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:03,778: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:04,009: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:04,178: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:04,356: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:04,550: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:04,819: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:05,083: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:05,316: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:05,511: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:05,715: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:05,956: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:12,158: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:19,326: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:20,099: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:20,474: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:20,711: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:20,903: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:21,433: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:21,957: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:25:22,509: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:26:23,281: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:26:27,653: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:27:30,690: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:27:32,536: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:27:33,059: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:27:33,263: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:27:33,457: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:27:33,689: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:27:33,885: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:27:34,084: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:27:34,269: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:26,930: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:31,595: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:37,253: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:38,440: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:38,896: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:39,125: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:39,303: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:39,491: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:55,386: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:56,760: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:56,969: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:57,148: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:57,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:57,522: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:57,705: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:57,890: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:58,068: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:58,242: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:58,400: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:58,603: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:58,775: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:58,976: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:59,135: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:59,332: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:59,509: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:28:59,707: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:29:00,086: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:29:00,251: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:29:16,689: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:29:37,358: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:29:40,802: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:29:42,098: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:29:42,337: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:29:45,873: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:29:48,154: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:30:46,212: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:38:32,648: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:43:01,501: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:43:19,842: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:43:24,129: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:45:39,763: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:45:48,866: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:45:49,867: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:45:50,513: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:45:51,180: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:46:13,022: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:46:15,086: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:46:15,655: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:06,789: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:08,252: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:09,367: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:09,971: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:10,153: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:10,315: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:10,477: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:27,881: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:29,166: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:29,596: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:29,781: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:29,939: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:30,111: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:30,279: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:30,469: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:30,590: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:30,755: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:30,942: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:47:55,219: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:48:03,847: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:48:04,936: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:51:37,772: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 11:51:37,795: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.17:8080]
[2024-12-13 11:51:37,795: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-12-13 11:51:39,260: INFO: _internal: 127.0.0.1 - - [13/Dec/2024 11:51:39] "GET / HTTP/1.1" 200 -]
[2024-12-13 11:51:44,019: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\KidneyProject\Kidney-Disease-Classification-Project\venv\lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\KidneyProject\Kidney-Disease-Classification-Project\venv\lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\KidneyProject\Kidney-Disease-Classification-Project\venv\lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\KidneyProject\Kidney-Disease-Classification-Project\venv\lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\KidneyProject\Kidney-Disease-Classification-Project\venv\lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\KidneyProject\Kidney-Disease-Classification-Project\venv\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "D:\MY FOLDER\MY LEARNING\TTNamUS\KidneyProject\Kidney-Disease-Classification-Project\app.py", line 86, in predictRoute
    decodeImage(image, clApp.filename)
  File "d:\my folder\my learning\ttnamus\kidneyproject\kidney-disease-classification-project\src\cnnClassifier\utils\common.py", line 129, in decodeImage
    imgdata = base64.b64decode(imgstring.split(",")[1])
IndexError: list index out of range
[2024-12-13 11:51:44,023: INFO: _internal: 127.0.0.1 - - [13/Dec/2024 11:51:44] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-12-13 13:00:36,540: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:01:58,986: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:02:36,090: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:04:25,121: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:04:25,550: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 13:04:43,564: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:04:43,743: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 13:04:51,449: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:04:51,638: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 13:14:14,041: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:14:14,308: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 13:14:18,784: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:14:18,975: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 13:16:57,193: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:16:57,480: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 13:16:59,555: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:16:59,737: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 13:18:25,528: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:18:25,727: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 13:18:35,162: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:18:35,347: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 13:18:36,731: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:18:36,916: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 13:18:37,388: WARNING: polymorphic_function: 5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000025524BDD7E0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-12-13 13:18:39,434: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:18:39,618: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 13:18:40,073: WARNING: polymorphic_function: 6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x0000025524C3AB00> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-12-13 13:18:40,949: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:18:41,316: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 13:18:42,696: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:18:42,880: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 13:18:43,706: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:18:43,890: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 13:34:12,584: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:34:12,772: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-12-13 13:34:17,190: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-12-13 13:34:17,384: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
